name: "vocoder"
backend: "python"
max_batch_size: 1

dynamic_batching {
  preferred_batch_size: [1]
  max_queue_delay_microseconds: 0
  priority_levels: 100
  default_priority_level: 100
}

parameters [
  {
    key: "model_dir"
    value: { string_value: "/workspace/CosyVoice/runtime/triton_trtllm/Fun-CosyVoice3-0.5B-2512" }
  }
]

input [
  {
    name: "mel"
    data_type: TYPE_FP32
    dims: [80, -1]
  },
  {
    name: "mel_len"
    data_type: TYPE_INT32
    dims: [1]
    optional: true
  },
  {
    name: "finalize"
    data_type: TYPE_BOOL
    dims: [1]
    reshape: { shape: [] }
  }
]

output [
  {
    name: "tts_speech"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]
